"""empty message

Revision ID: 01f0936bd739
Revises: 4be5155bbe68
Create Date: 2024-12-29 18:13:51.604995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01f0936bd739"
down_revision: Union[str, None] = "4be5155bbe68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Chats",
        sa.Column("chat_title", sa.String(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("chat_context", sa.String(), nullable=False),
        sa.Column("chat_number_of_users", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Chats")
    # ### end Alembic commands ###
