"""Update Chat model to include chat_title & chat_context

Revision ID: 4be5155bbe68
Revises: 561668800f8c
Create Date: 2024-12-08 02:57:09.215666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4be5155bbe68"
down_revision: Union[str, None] = "561668800f8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Chats", sa.Column("chat_title", sa.String(), nullable=False))
    op.add_column(
        "Chats", sa.Column("chat_number_of_users", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Chats", "chat_number_of_users")
    op.drop_column("Chats", "chat_title")
    # ### end Alembic commands ###
