name: Playwright Tests
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./view/web
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Next.js application
        working-directory: ./view/web
        run: npm run build
      - name: Start Next.js server and run tests
        working-directory: ./view/web
        run: |
          # Start server in background
          npm run start -- --port 3000 > server.log 2>&1 &
          
          # Wait for server to be ready
          npx wait-on http://localhost:3000
          
          # Run Playwright tests
          npx playwright test --project=chromium --project=firefox
          
          # Kill the server process
          kill $!
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./view/web/playwright-report/
          retention-days: 30