name: Playwright Tests
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./view/web
        run: npm ci
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}
          restore-keys: |
            playwright-
      - name: Install Playwright Browsers (if needed)
        run: npx playwright install --with-deps

      - name: Build Next.js application
        working-directory: ./view/web
        env:
          T_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_T_BACKEND_URL }}
          NEXT_PUBLIC_T_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_T_BACKEND_URL }}
        run: npm run build
      - name: Start Next.js server and run tests
        working-directory: ./view/web
        run: |
          # Start server in background
          npm run start -- --port 3000 > server.log 2>&1 &

          # Wait for server to be ready
          npx wait-on http://localhost:3000

          # Run Playwright tests
          npx playwright test --project=chromium --project=firefox

          # Kill the server process
          kill $!
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./view/web/playwright-report/
          retention-days: 30
